
#############################
###### MSCI FUNCTIONS #######
#############################

# Download data
msci.download <- function(countries,
						  startDate = "1969-12-29",
						  endDate = Sys.Date(),
						  priceLevel = "41",
						  currency = "15",
						  baseValue = "true",
						  annual = FALSE,
						  change = FALSE,
						  rank = FALSE) {
	# Setup
	require(quantmod)
	options(stringsAsFactors = FALSE)
	
	
	# load download code dataframe
	codeDF <- msci.list()
					  
	# extra codes given by user
	codes <- codeDF[codeDF$Country.Code %in% countries,]
	
	# Convert start and end dates to URL format
		# start date
		startdate <- as.Date(startDate)
		startchar <- format(startdate, format = "%d %b, %Y")
		startchar <- gsub(" ","%20",startchar)
		# end date
		enddate <- as.Date(endDate)
		endchar <- format(enddate, format = "%d %b, %Y")
		endchar <- gsub(" ","%20",endchar)
	
	# construct the URL
	URL <- paste0("https://www.msci.com/webapp/indexperf/charts?indices=",
					paste(codes$Download.Code, collapse = "|"),
					"&startDate=",
					startchar,
					"&endDate=",
					endchar,
					"&priceLevel=",
					priceLevel,
					"&currency=",
					currency,
					"&frequency=D&scope=R&format=XLS&baseValue=",
					baseValue,
					"&site=gimi")
	
	
	### Download and Process Initial Data ###
		# Download file
		download.file(URL, destfile = "msci file.xls", mode = "wb")
		# Load file into variable
		msciWB <- XLConnect::loadWorkbook("msci file.xls")
		# Extract sheet from WB
		index <- XLConnect::readWorksheet(msciWB, sheet = 1, startRow = 7)
		# Subset resulting DF to not include Copyright text at the bottom
		index <- index[1:(as.numeric(head(rownames(index[is.na(index$Date),]),1)) - 1), ]
	
		
	### Replace column names with user's codes ###
		# create named vector of country codes
		codesvec <- codes$Country.Code
		names(codesvec) <- codes$Col.Name
		# Replace index names with country codes by looking them up from named vector
		names(index) <- c("Date",codesvec[names(index)[-1]])
	
		
	### Further Processing ###
		#Convert to date
		index$Date <- as.Date(index$Date)
		# Fill in blanks
		if(length(countries)>1) {
			index[, -1] <- apply(index[, -1], 2, na.locf, na.rm = FALSE, maxgap = 12)
		} else {
			index[,2] <- na.locf(index[,2], na.rm = FALSE, maxgap = 12)
		}
		
	# Remove file after finishing
	file.remove("msci file.xls")
	
	
	#### Conditional Transformations ####
	
	## Convert to annual if requested
	if(annual) {
		index <- index[format(index$Date, format = "%m") == "12", ]
		index$Date <- format(index$Date, format = "%Y")
	}
	
	## Convert to % change if requested
	if(change) {
		if(length(countries) > 1) {
			index[, -1] <- apply(index[,-1], 2, Delt)
		} else {
			index[,2] <- as.numeric(Delt(index[,2]))
		}
	}
	
	## Convert to rank if requested
	if(rank) {
		# If more than 1 country, convert to rank
		if(length(countries) > 1) {
			index[, -1] <- t(apply(index[, -1], 1, function(x) rank(-x, na.last = "keep", ties.method = "min")))
		} else {
			# If only one country, return warning
			warning("Only one index downloaded, returning unranked value.")
		}
	}
	
	return(index)
}


# List countries with download codes
msci.list <- function() {
	## Create download code dataframe
	Country <- c("Australia",
			"Austria",
			"Belgium",
			"Brazil",
			"Canada",
			"Chile",
			"China",
			"Colombia",
			"Czech Republic",
			"Denmark",
			"Egypt",
			"Finland",
			"France",
			"Germany",
			"Greece",
			"Hong Kong",
			"Hungary",
			"India",
			"Indonesia",
			"Ireland",
			"Israel",
			"Italy",
			"Japan",
			"Korea, Republic of",
			"Malaysia",
			"Mexico",
			"Netherlands",
			"New Zealand",
			"Norway",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Qatar",
			"Russian Federation",
			"Singapore",
			"South Africa",
			"Spain",
			"Sweden",
			"Switzerland",
			"Taiwan, Province of China",
			"Thailand",
			"Turkey",
			"United Arab Emirates",
			"United Kingdom",
			"United States",
			"EAFE",
			"Emerging",
			"Developed",
			"Australia",
			"Austria",
			"Belgium",
			"Brazil",
			"Canada",
			"Chile",
			"China",
			"Colombia",
			"Czech Republic",
			"Denmark",
			"Egypt",
			"Finland",
			"France",
			"Germany",
			"Greece",
			"Hong Kong",
			"Hungary",
			"India",
			"Indonesia",
			"Ireland",
			"Israel",
			"Italy",
			"Japan",
			"Korea, Republic of",
			"Malaysia",
			"Mexico",
			"Netherlands",
			"New Zealand",
			"Norway",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Qatar",
			"Russian Federation",
			"Singapore",
			"South Africa",
			"Spain",
			"Sweden",
			"Switzerland",
			"Taiwan, Province of China",
			"Thailand",
			"Turkey",
			"United Arab Emirates",
			"United Kingdom",
			"United States",
			"Emerging",
			"Developed",
			"Americas",
			"Asia-Pacific",
			"Europe",
			"Australia",
			"Austria",
			"Belgium",
			"Brazil",
			"Canada",
			"Chile",
			"China",
			"Colombia",
			"Czech Republic",
			"Denmark",
			"Egypt",
			"Finland",
			"France",
			"Germany",
			"Greece",
			"Hong Kong",
			"Hungary",
			"India",
			"Indonesia",
			"Ireland",
			"Israel",
			"Italy",
			"Japan",
			"Korea, Republic of",
			"Malaysia",
			"Mexico",
			"Netherlands",
			"New Zealand",
			"Norway",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Qatar",
			"Russian Federation",
			"Singapore",
			"South Africa",
			"Spain",
			"Sweden",
			"Switzerland",
			"Taiwan, Province of China",
			"Thailand",
			"Turkey",
			"United Arab Emirates",
			"United Kingdom",
			"United States",
			"Emerging",
			"Developed",
			"Americas",
			"Asia-Pacific",
			"Europe",
			"United States",
			"United States",
			"United States",
			"United States")
	
	
	Col.Name <- c("AUSTRALIA.Standard..Large.Mid.Cap..",
			"AUSTRIA.Standard..Large.Mid.Cap..",
			"BELGIUM.Standard..Large.Mid.Cap..",
			"BRAZIL.Standard..Large.Mid.Cap..",
			"CANADA.Standard..Large.Mid.Cap..",
			"CHILE.Standard..Large.Mid.Cap..",
			"CHINA.Standard..Large.Mid.Cap..",
			"COLOMBIA.Standard..Large.Mid.Cap..",
			"CZECH.REPUBLIC.Standard..Large.Mid.Cap..",
			"DENMARK.Standard..Large.Mid.Cap..",
			"EGYPT.Standard..Large.Mid.Cap..",
			"FINLAND.Standard..Large.Mid.Cap..",
			"FRANCE.Standard..Large.Mid.Cap..",
			"GERMANY.Standard..Large.Mid.Cap..",
			"GREECE.Standard..Large.Mid.Cap..",
			"HONG.KONG.Standard..Large.Mid.Cap..",
			"HUNGARY.Standard..Large.Mid.Cap..",
			"INDIA.Standard..Large.Mid.Cap..",
			"INDONESIA.Standard..Large.Mid.Cap..",
			"IRELAND.Standard..Large.Mid.Cap..",
			"ISRAEL.Standard..Large.Mid.Cap..",
			"ITALY.Standard..Large.Mid.Cap..",
			"JAPAN.Standard..Large.Mid.Cap..",
			"KOREA.Standard..Large.Mid.Cap..",
			"MALAYSIA.Standard..Large.Mid.Cap..",
			"MEXICO.Standard..Large.Mid.Cap..",
			"NETHERLANDS.Standard..Large.Mid.Cap..",
			"NEW.ZEALAND.Standard..Large.Mid.Cap..",
			"NORWAY.Standard..Large.Mid.Cap..",
			"PERU.Standard..Large.Mid.Cap..",
			"PHILIPPINES.Standard..Large.Mid.Cap..",
			"POLAND.Standard..Large.Mid.Cap..",
			"PORTUGAL.Standard..Large.Mid.Cap..",
			"QATAR.Standard..Large.Mid.Cap..",
			"RUSSIA.ADR.GDR.Standard..Large.Mid.Cap..",
			"SINGAPORE.Standard..Large.Mid.Cap..",
			"SOUTH.AFRICA.Standard..Large.Mid.Cap..",
			"SPAIN.Standard..Large.Mid.Cap..",
			"SWEDEN.Standard..Large.Mid.Cap..",
			"SWITZERLAND.Standard..Large.Mid.Cap..",
			"TAIWAN.Standard..Large.Mid.Cap..",
			"THAILAND.Standard..Large.Mid.Cap..",
			"TURKEY.Standard..Large.Mid.Cap..",
			"UNITED.ARAB.EMIRATES.Standard..Large.Mid.Cap..",
			"UNITED.KINGDOM.Standard..Large.Mid.Cap..",
			"USA.Standard..Large.Mid.Cap..",
			"EAFE.Standard..Large.Mid.Cap..",
			"EM..EMERGING.MARKETS..Standard..Large.Mid.Cap..",
			"WORLD.Standard..Large.Mid.Cap..",
			"AUSTRALIA.VALUE.Standard..Large.Mid.Cap..Value",
			"AUSTRIA.VALUE.Standard..Large.Mid.Cap..Value",
			"BELGIUM.VALUE.Standard..Large.Mid.Cap..Value",
			"BRAZIL.VALUE.Standard..Large.Mid.Cap..Value",
			"CANADA.VALUE.Standard..Large.Mid.Cap..Value",
			"CHILE.VALUE.Standard..Large.Mid.Cap..Value",
			"CHINA.VALUE.Standard..Large.Mid.Cap..Value",
			"COLOMBIA.VALUE.Standard..Large.Mid.Cap..Value",
			"CZECH.REPUBLIC.VALUE.Standard..Large.Mid.Cap..Value",
			"DENMARK.VALUE.Standard..Large.Mid.Cap..Value",
			"EGYPT.VALUE.Standard..Large.Mid.Cap..Value",
			"FINLAND.VALUE.Standard..Large.Mid.Cap..Value",
			"FRANCE.VALUE.Standard..Large.Mid.Cap..Value",
			"GERMANY.VALUE.Standard..Large.Mid.Cap..Value",
			"GREECE.VALUE.Standard..Large.Mid.Cap..Value",
			"HONG.KONG.VALUE.Standard..Large.Mid.Cap..Value",
			"HUNGARY.VALUE.Standard..Large.Mid.Cap..Value",
			"INDIA.VALUE.Standard..Large.Mid.Cap..Value",
			"INDONESIA.VALUE.Standard..Large.Mid.Cap..Value",
			"IRELAND.VALUE.Standard..Large.Mid.Cap..Value",
			"ISRAEL.VALUE.Standard..Large.Mid.Cap..Value",
			"ITALY.VALUE.Standard..Large.Mid.Cap..Value",
			"JAPAN.VALUE.Standard..Large.Mid.Cap..Value",
			"KOREA.VALUE.Standard..Large.Mid.Cap..Value",
			"MALAYSIA.VALUE.Standard..Large.Mid.Cap..Value",
			"MEXICO.VALUE.Standard..Large.Mid.Cap..Value",
			"NETHERLANDS.VALUE.Standard..Large.Mid.Cap..Value",
			"NEW.ZEALAND.VALUE.Standard..Large.Mid.Cap..Value",
			"NORWAY.VALUE.Standard..Large.Mid.Cap..Value",
			"PERU.VALUE.Standard..Large.Mid.Cap..Value",
			"PHILIPPINES.VALUE.Standard..Large.Mid.Cap..Value",
			"POLAND.VALUE.Standard..Large.Mid.Cap..Value",
			"PORTUGAL.VALUE.Standard..Large.Mid.Cap..Value",
			"QATAR.VALUE.Standard..Large.Mid.Cap..Value",
			"RUSSIA.VALUE.Standard..Large.Mid.Cap..Value",
			"SINGAPORE.VALUE.Standard..Large.Mid.Cap..Value",
			"SOUTH.AFRICA.VALUE.Standard..Large.Mid.Cap..Value",
			"SPAIN.VALUE.Standard..Large.Mid.Cap..Value",
			"SWEDEN.VALUE.Standard..Large.Mid.Cap..Value",
			"SWITZERLAND.VALUE.Standard..Large.Mid.Cap..Value",
			"TAIWAN.VALUE.Standard..Large.Mid.Cap..Value",
			"THAILAND.VALUE.Standard..Large.Mid.Cap..Value",
			"TURKEY.VALUE.Standard..Large.Mid.Cap..Value",
			"UNITED.ARAB.EMIRATES.VALUE.Standard..Large.Mid.Cap..Value",
			"UNITED.KINGDOM.VALUE.Standard..Large.Mid.Cap..Value",
			"USA.VALUE.Standard..Large.Mid.Cap..Value",
			"EM..EMERGING.MARKETS..VALUE.Standard..Large.Mid.Cap..Value",
			"WORLD.VALUE.Standard..Large.Mid.Cap..Value",
			"AC.AMERICAS.VALUE.Standard..Large.Mid.Cap..Value",
			"AC.ASIA.PACIFIC.VALUE.Standard..Large.Mid.Cap..Value",
			"AC.EUROPE.VALUE.Standard..Large.Mid.Cap..",
			"AUSTRALIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"AUSTRIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"BELGIUM.GROWTH.Standard..Large.Mid.Cap..Growth",
			"BRAZIL.GROWTH.Standard..Large.Mid.Cap..Growth",
			"CANADA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"CHILE.GROWTH.Standard..Large.Mid.Cap..Growth",
			"CHINA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"COLOMBIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"CZECH.REPUBLIC.GROWTH.Standard..Large.Mid.Cap..Growth",
			"DENMARK.GROWTH.Standard..Large.Mid.Cap..Growth",
			"EGYPT.GROWTH.Standard..Large.Mid.Cap..Growth",
			"FINLAND.GROWTH.Standard..Large.Mid.Cap..Growth",
			"FRANCE.GROWTH.Standard..Large.Mid.Cap..Growth",
			"GERMANY.GROWTH.Standard..Large.Mid.Cap..Growth",
			"GREECE.GROWTH.Standard..Large.Mid.Cap..Growth",
			"HONG.KONG.GROWTH.Standard..Large.Mid.Cap..Growth",
			"HUNGARY.GROWTH.Standard..Large.Mid.Cap..Growth",
			"INDIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"INDONESIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"IRELAND.GROWTH.Standard..Large.Mid.Cap..Growth",
			"ISRAEL.GROWTH.Standard..Large.Mid.Cap..Growth",
			"ITALY.GROWTH.Standard..Large.Mid.Cap..Growth",
			"JAPAN.GROWTH.Standard..Large.Mid.Cap..Growth",
			"KOREA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"MALAYSIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"MEXICO.GROWTH.Standard..Large.Mid.Cap..Growth",
			"NETHERLANDS.GROWTH.Standard..Large.Mid.Cap..Growth",
			"NEW.ZEALAND.GROWTH.Standard..Large.Mid.Cap..Growth",
			"NORWAY.GROWTH.Standard..Large.Mid.Cap..Growth",
			"PERU.GROWTH.Standard..Large.Mid.Cap..Growth",
			"PHILIPPINES.GROWTH.Standard..Large.Mid.Cap..Growth",
			"POLAND.GROWTH.Standard..Large.Mid.Cap..Growth",
			"PORTUGAL.GROWTH.Standard..Large.Mid.Cap..Growth",
			"QATAR.GROWTH.Standard..Large.Mid.Cap..Growth",
			"RUSSIA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"SINGAPORE.GROWTH.Standard..Large.Mid.Cap..Growth",
			"SOUTH.AFRICA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"SPAIN.GROWTH.Standard..Large.Mid.Cap..Growth",
			"SWEDEN.GROWTH.Standard..Large.Mid.Cap..Growth",
			"SWITZERLAND.GROWTH.Standard..Large.Mid.Cap..Growth",
			"TAIWAN.GROWTH.Standard..Large.Mid.Cap..Growth",
			"THAILAND.GROWTH.Standard..Large.Mid.Cap..Growth",
			"TURKEY.GROWTH.Standard..Large.Mid.Cap..Growth",
			"UNITED.ARAB.EMIRATES.GROWTH.Standard..Large.Mid.Cap..Growth",
			"UNITED.KINGDOM.GROWTH.Standard..Large.Mid.Cap..Growth",
			"USA.GROWTH.Standard..Large.Mid.Cap..Growth",
			"EM..EMERGING.MARKETS..GROWTH.Standard..Large.Mid.Cap..Growth",
			"WORLD.GROWTH.Standard..Large.Mid.Cap..Growth",
			"AC.AMERICAS.GROWTH.Standard..Large.Mid.Cap..Growth",
			"AC.ASIA.PACIFIC.GROWTH.Standard..Large.Mid.Cap..Growth",
			"AC.EUROPE.GROWTH.Standard..Large.Mid.Cap..",
			"USA.LARGE.GROWTH.Large.Cap.Growth",
			"USA.LARGE.VALUE.Large.Cap.Value",
			"USA.SMALL.GROWTH.Small.Cap.Growth",
			"USA.SMALL.VALUE.Small.Cap.Value")
	
	Country.Code <- c("AU_A",
			"AT_A",
			"BE_A",
			"BR_A",
			"CA_A",
			"CL_A",
			"CN_A",
			"CO_A",
			"CZ_A",
			"DK_A",
			"EG_A",
			"FI_A",
			"FR_A",
			"DE_A",
			"GR_A",
			"HK_A",
			"HU_A",
			"IN_A",
			"ID_A",
			"IE_A",
			"IL_A",
			"IT_A",
			"JP_A",
			"KR_A",
			"MY_A",
			"MX_A",
			"NL_A",
			"NZ_A",
			"NO_A",
			"PE_A",
			"PH_A",
			"PL_A",
			"PT_A",
			"QA_A",
			"RU_A",
			"SG_A",
			"ZA_A",
			"ES_A",
			"SE_A",
			"CH_A",
			"TW_A",
			"TH_A",
			"TR_A",
			"AE_A",
			"GB_A",
			"US_A",
			"__EAFE_A",
			"__EM_A",
			"__DM_A",
			"AU_V",
			"AT_V",
			"BE_V",
			"BR_V",
			"CA_V",
			"CL_V",
			"CN_V",
			"CO_V",
			"CZ_V",
			"DK_V",
			"EG_V",
			"FI_V",
			"FR_V",
			"DE_V",
			"GR_V",
			"HK_V",
			"HU_V",
			"IN_V",
			"ID_V",
			"IE_V",
			"IL_V",
			"IT_V",
			"JP_V",
			"KR_V",
			"MY_V",
			"MX_V",
			"NL_V",
			"NZ_V",
			"NO_V",
			"PE_V",
			"PH_V",
			"PL_V",
			"PT_V",
			"QA_V",
			"RU_V",
			"SG_V",
			"ZA_V",
			"ES_V",
			"SE_V",
			"CH_V",
			"TW_V",
			"TH_V",
			"TR_V",
			"AE_V",
			"GB_V",
			"US_V",
			"__EM_V",
			"__DM_V",
			"__AM_V",
			"__AP_V",
			"__EU_V",
			"AU_G",
			"AT_G",
			"BE_G",
			"BR_G",
			"CA_G",
			"CL_G",
			"CN_G",
			"CO_G",
			"CZ_G",
			"DK_G",
			"EG_G",
			"FI_G",
			"FR_G",
			"DE_G",
			"GR_G",
			"HK_G",
			"HU_G",
			"IN_G",
			"ID_G",
			"IE_G",
			"IL_G",
			"IT_G",
			"JP_G",
			"KR_G",
			"MY_G",
			"MX_G",
			"NL_G",
			"NZ_G",
			"NO_G",
			"PE_G",
			"PH_G",
			"PL_G",
			"PT_G",
			"QA_G",
			"RU_G",
			"SG_G",
			"ZA_G",
			"ES_G",
			"SE_G",
			"CH_G",
			"TW_G",
			"TH_G",
			"TR_G",
			"AE_G",
			"GB_G",
			"US_G",
			"__EM_G",
			"__DM_G",
			"__AM_G",
			"__AP_G",
			"__EU_G",
			"US_L_G",
			"US_L_V",
			"US_S_G",
			"US_S_V")
	
	Download.Code <- c("60,C,30",
			"61,C,30",
			"62,C,30",
			"63,C,30",
			"64,C,30",
			"65,C,30",
			"2713,C,30",
			"1890,C,30",
			"68,C,30",
			"69,C,30",
			"2877,C,30",
			"70,C,30",
			"71,C,30",
			"73,C,30",
			"1146,C,30",
			"75,C,30",
			"76,C,30",
			"77,C,30",
			"2879,C,30",
			"79,C,30",
			"2352,C,30",
			"81,C,30",
			"83,C,30",
			"85,C,30",
			"2880,C,30",
			"2,C,30",
			"89,C,30",
			"90,C,30",
			"91,C,30",
			"2323,C,30",
			"4,C,30",
			"95,C,30",
			"1190,C,30",
			"25558,C,30",
			"92392,C,30",
			"181,C,30",
			"2428,C,30",
			"98,C,30",
			"99,C,30",
			"100,C,30",
			"66,C,30",
			"2881,C,30",
			"102,C,30",
			"25560,C,30",
			"103,C,30",
			"104,C,30",
			"108,C,30",
			"13,C,30",
			"106,C,30",
			"2897,V,30",
			"2899,V,30",
			"2901,V,30",
			"3003,V,30",
			"2903,V,30",
			"3005,V,30",
			"3007,V,30",
			"3009,V,30",
			"3011,V,30",
			"2905,V,30",
			"3013,V,30",
			"2909,V,30",
			"2911,V,30",
			"2913,V,30",
			"3015,V,30",
			"2915,V,30",
			"3017,V,30",
			"3019,V,30",
			"3021,V,30",
			"2917,V,30",
			"3025,V,30",
			"2919,V,30",
			"2921,V,30",
			"3031,V,30",
			"17251,V,30",
			"3037,V,30",
			"2927,V,30",
			"2929,V,30",
			"2933,V,30",
			"3043,V,30",
			"3045,V,30",
			"3049,V,30",
			"3051,V,30",
			"104963,V,30",
			"3053,V,30",
			"2937,V,30",
			"3055,V,30",
			"2939,V,30",
			"2943,V,30",
			"2947,V,30",
			"3061,V,30",
			"3063,V,30",
			"3067,V,30",
			"104975,V,30",
			"2949,V,30",
			"2951,V,30",
			"3173,V,30",
			"2993,V,30",
			"3075,V,36",
			"3094,V,36",
			"3103,C,36",
			"2896,G,30",
			"2898,G,30",
			"2900,G,30",
			"3002,G,30",
			"2902,G,30",
			"3004,G,30",
			"3006,G,30",
			"3008,G,30",
			"3010,G,30",
			"2904,G,30",
			"3012,G,30",
			"2908,G,30",
			"2910,G,30",
			"2912,G,30",
			"3014,G,30",
			"2914,G,30",
			"3016,G,30",
			"3018,G,30",
			"3020,G,30",
			"2916,G,30",
			"3024,G,30",
			"2918,G,30",
			"2920,G,30",
			"3030,G,30",
			"17250,G,30",
			"3036,G,30",
			"2926,G,30",
			"2928,G,30",
			"2932,G,30",
			"3042,G,30",
			"3044,G,30",
			"3048,G,30",
			"3050,G,30",
			"104952,G,30",
			"3052,G,30",
			"2936,G,30",
			"3054,G,30",
			"2938,G,30",
			"2942,G,30",
			"2946,G,30",
			"3060,G,30",
			"3062,G,30",
			"3066,G,30",
			"104964,G,30",
			"2948,G,30",
			"2950,G,30",
			"3172,G,30",
			"2992,G,30",
			"3074,G,36",
			"3093,G,36",
			"3102,C,36",
			"59608,G,31",
			"59503,V,31",
			"64596,G,33",
			"64491,V,33")
	
	codeDF <- data.frame(Country = Country,
			Col.Name = Col.Name,
			Country.Code = Country.Code,
			Download.Code = Download.Code)
	
	return(codeDF)
}
